version: '3'
services:
  generator:
    build: ./generator
    ports:
      - "5000:5000"
 
  invoker:
    build: ./invoker
    ports:
      - "5001:5001"
    depends_on:
      - generator
      - redis
 
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
